# Generated by Django 4.0.6 on 2022-08-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihy', '0002_alter_kniha_jmeno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kniha',
            options={'verbose_name_plural': 'Knihy'},
        ),
        migrations.AddField(
            model_name='kniha',
            name='autor',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
