# Generated by Django 4.0.6 on 2022-08-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihy', '0003_alter_kniha_options_kniha_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='kniha',
            name='rok',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
